lista_de_convidados = ['Elon Musk', 'Duda Matte', 'Jesus Cristo', 'Eminem']
print(f'Salve, {lista_de_convidados[0]}. Venho por meio dessa mensagem tá te convidando ai pra uma janta deliciossima na minha goma, espero que você brote, quero muito conversar com você sobre coisas do futuro.\n')
print(f'Salve, {lista_de_convidados[1]}. Venho por meio dessa mensagem primeiramente pra falar que você é muito bonita e queria tá ai te convidando pra gente troca umas ideia na minha goma e pa. Tmj\n')
print(f'Salve, {lista_de_convidados[2]}. Venho por meio dessa mensagem estar ai te convidando pra uma janta, espero que o senhor compareça, sempre quis falar muito com o senhor, pelo que eu sei você é uma pessoa muito inteligente e seria um prazer te ter aqui na minha goma, tmj Jesus.\n')
print(f'Salve, {lista_de_convidados[3]}. Venho por meio dessa mensagem te convidar para um jantar, já que o Sócrates não pode vir, é claro que eu gosto muito de você, mas só havia 4 vagas e depois pensei em você. Espero que compareça, gosto muito do seu trabalho.\n')
print(f'Boa tarde {lista_de_convidados}, encontrei uma mesa de jantar maior, então irei chamar mais pessoa.\n')
lista_de_convidados.insert(1, 'Monark')
lista_de_convidados.insert(4, 'Augusto Cury')
lista_de_convidados.append('Marcelinho Carioca')
print(f'Salve, {lista_de_convidados[0]}. Venho por meio dessa mensagem tá te convidando ai pra uma janta deliciossima na minha goma, espero que você brote, quero muito conversar com você sobre coisas do futuro.\n')
print(f'Salve, {lista_de_convidados[1]}. Venho por meio dessa mensagem te convidar pra uma janta, já que você é uma pessoa muito legal e eu consegui mais 3 vagas.\n')
print(f'Salve, {lista_de_convidados[2]}. Venho por meio dessa mensagem primeiramente pra falar que você é muito bonita e queria tá ai te convidando pra gente troca umas ideia na minha goma e pa. Tmj\n')
print(f'Salve, {lista_de_convidados[3]}. Venho por meio dessa mensagem estar ai te convidando pra uma janta, espero que o senhor compareça, sempre quis falar muito com o senhor, pelo que eu sei você é uma pessoa muito inteligente e seria um prazer te ter aqui na minha goma, tmj Jesus.\n')
print(f'Salve, {lista_de_convidados[4]}. Venho por meio dessa mensagem chamar você para uma janta aqui em casa, passar umas ideia pra gente do psicológico, sei que você manda muito nessa área, tmj.')
print(f'Salve, {lista_de_convidados[5]}. Venho por meio dessa mensagem te convidar para um jantar, já que o Sócrates não pode vir, é claro que eu gosto muito de você, mas só havia 4 vagas e depois pensei em você. Espero que compareça, gosto muito do seu trabalho.\n')
print(f'Salve, {lista_de_convidados[6]}. Venho por meio dessa mensagem te convidar pra uma janta aqui em casa, sei que você manja de uns exercícios ai, espero que brote pra passar uns exercícios pra gente depois da comida.\n')